name: Build Electron App

on:
  push:
    branches: [main, master, dev]
  pull_request:
    branches: [main, master, dev]
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        include:
          - os: windows-latest
            app: backoffice
            build_script: 'build:electron'
            artifact_name: 'backoffice-windows'
          - os: windows-latest
            app: headoffice
            build_script: 'build:electron:headoffice'
            artifact_name: 'headoffice-windows'
          - os: macos-latest
            app: backoffice
            build_script: 'build:electron:mac'
            artifact_name: 'backoffice-macos'
          - os: macos-latest
            app: headoffice
            build_script: 'build:electron:headoffice:mac'
            artifact_name: 'headoffice-macos'

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build React app
        run: npm run build:local

      - name: Build Electron app (${{ matrix.app }})
        run: npm run ${{ matrix.build_script }}
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.artifact_name }}
          path: dist/
